### ISSUE TITLE
'Call Now' Text Needs to be Centered

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#22]
![image-1 copy](https://user-images.githubusercontent.com/31627480/48158796-af5bd800-e290-11e8-9835-b476a98925a5.jpeg)

Please review screenshot

**Comment by lukemiller** [comment]
fixed

**Comment by cunning-folk** [comment]
im still seeing this one. the client will seize on this because its the call to action.
